version: '3'

services:
  app:
    image: lsml_final
    deploy:
      replicas: 2
    networks:
      - webnet

  nginx-lb:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
